name: pd_detector
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - autopep8=1.6.0
  - isort=5.9.3
  - matplotlib=3.7.2
  - pandas=2.0.3
  - pip=23.2.1
  - pylint=2.16.2
  - pytest=7.4.0
  - pytest-cov=4.0.0
  - python=3.11.4
  - scipy=1.11.1
  - setuptools=68.0.0
  - pip:
    - bandit==1.7.5